spring.application.name=vpp-backend

supabase.url=${SPRING_DATASOURCE_URL}
supabase.key=${SPRING_DATASOURCE_KEY}
supabase.secret.key=${SPRING_DATASOURCE_SECRET_KEY}

app.frontend.url=${APP_FRONT_END_URL}

spring.mail.host=${SPRING_DATASOURCE_HOST}
spring.mail.port=${SPRING_DATASOURCE_PORT}
spring.mail.username=${SPRING_DATASOURCE_USERNAME}
spring.mail.password=${SPRING_DATASOURCE_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
