spring.application.name=vpp-backend

supabase.url=${SPRING_DATASOURCE_URL}
supabase.key=${SPRING_DATASOURCE_KEY}
supabase.secret.key=${SPRING_DATASOURCE_SECRET_KEY}

app.frontend.url=${APP_FRONT_END_URL}
